// <auto-generated />
using BikeWatcher.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BikeWatcher.Migrations
{
    [DbContext(typeof(StationContext))]
    [Migration("20200226101014_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BikeWatcher.Models.Stations", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("availability")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("availabilitycode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("available_bike_stands")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("available_bikes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("banking")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bike_stands")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bonus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("code_insee")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("commune")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("enddate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("etat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("langue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("last_update")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("last_update_fme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lng")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nmarrond")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("startdate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("titre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Stations");
                });
#pragma warning restore 612, 618
        }
    }
}
